export const companies = [
  {
    id: "nova-ai",
    name: "Nova AI",
    tagline: "Autonomous AI agents for enterprise workflow automation",
    sector: "AI/ML",
    stage: "Series A",
    geography: "USA",
    matchScore: 94,
    investmentScore: 87,
    founded: 2023,
    employees: 48,
    lastRound: "$12M Series A",
    valuation: "$80M",
    revenue: "$2.4M ARR",
    growth: "+340% YoY",
    logo: "⚡",
    color: "#3D6FFF",
    bulls: [
      "Founding team from DeepMind + OpenAI, 3 prior exits",
      "Proprietary fine-tuning pipeline creates durable moat",
      "Enterprise contracts with Fortune 500 signed pre-launch",
    ],
    risks: ["Crowded market — 200+ competitors in AI automation"],
    founders: [
      { name: "Sarah Chen", role: "CEO", bg: "Ex-DeepMind Research Lead, PhD MIT" },
      { name: "Marcus Webb", role: "CTO", bg: "Ex-OpenAI, built GPT-4 fine-tuning infra" },
    ],
    market: { tam: "$47B", sam: "$8B", som: "$400M" },
    aiRec: "Strong Buy — technical moat + founder quality ranks in top 2% of pipeline",
    tags: ["AI", "Enterprise", "Automation", "B2B SaaS"],
  },
  {
    id: "helix-health",
    name: "Helix Health",
    tagline: "AI-powered diagnostics reducing misdiagnosis by 73%",
    sector: "HealthTech",
    stage: "Seed",
    geography: "UK",
    matchScore: 91,
    investmentScore: 82,
    founded: 2024,
    employees: 22,
    lastRound: "$4.5M Seed",
    valuation: "$28M",
    revenue: "$480K ARR",
    growth: "+180% YoY",
    logo: "🧬",
    color: "#22D46B",
    bulls: [
      "Clinical validation with 94% accuracy across 12 hospitals",
      "FDA breakthrough device designation in process",
      "NHS partnership letters of intent signed",
    ],
    risks: ["Regulatory approval timeline 18–24 months"],
    founders: [
      { name: "Dr. Priya Sharma", role: "CEO", bg: "Ex-NHS Consultant, Oxford Medical School" },
      { name: "Tom Briggs", role: "CTO", bg: "Ex-DeepMind Health, ML for diagnostics" },
    ],
    market: { tam: "$22B", sam: "$3.5B", som: "$180M" },
    aiRec: "Buy — strong clinical validation, regulatory risk manageable with right support",
    tags: ["HealthTech", "AI", "Diagnostics", "MedTech"],
  },
  {
    id: "finflow",
    name: "FinFlow",
    tagline: "Real-time treasury intelligence for mid-market CFOs",
    sector: "FinTech",
    stage: "Series A",
    geography: "UAE",
    matchScore: 89,
    investmentScore: 79,
    founded: 2022,
    employees: 67,
    lastRound: "$18M Series A",
    valuation: "$120M",
    revenue: "$5.8M ARR",
    growth: "+210% YoY",
    logo: "💎",
    color: "#F0C040",
    bulls: [
      "Market timing perfect — CFOs desperate for real-time cash visibility",
      "Average contract value $180K/year, 98% net retention",
      "MENA banking sector underserved by US competitors",
    ],
    risks: ["Geographic concentration risk in MENA"],
    founders: [
      { name: "Ahmed Al-Rashid", role: "CEO", bg: "Ex-Goldman Sachs, 15 yrs treasury" },
      { name: "Lisa Park", role: "CPO", bg: "Ex-Stripe, built Stripe Treasury" },
    ],
    market: { tam: "$15B", sam: "$2.2B", som: "$95M" },
    aiRec: "Buy — strong unit economics and defensible geography",
    tags: ["FinTech", "Treasury", "CFO", "MENA"],
  },
  {
    id: "atomspace",
    name: "AtomSpace",
    tagline: "Decentralized compute network for AI model training",
    sector: "Infrastructure",
    stage: "Pre-seed",
    geography: "Singapore",
    matchScore: 85,
    investmentScore: 71,
    founded: 2024,
    employees: 9,
    lastRound: "$1.2M Pre-seed",
    valuation: "$12M",
    revenue: "$80K ARR",
    growth: "+500% YoY",
    logo: "⚛️",
    color: "#FF8C42",
    bulls: [
      "Solving $40B GPU shortage problem with distributed compute",
      "Technical founder holds 4 patents in distributed systems",
      "Early traction with 3 AI labs as paying customers",
    ],
    risks: ["Very early stage, product still pre-product-market fit"],
    founders: [
      { name: "Kai Zhang", role: "CEO", bg: "Ex-NVIDIA Research, distributed systems PhD" },
    ],
    market: { tam: "$60B", sam: "$4B", som: "$120M" },
    aiRec: "Watch — exceptional technical founders, needs more PMF evidence",
    tags: ["Infrastructure", "AI", "Compute", "Web3"],
  },
  {
    id: "cortex-legal",
    name: "Cortex Legal",
    tagline: "AI that reviews contracts in 90 seconds vs 90 hours",
    sector: "LegalTech",
    stage: "Seed",
    geography: "USA",
    matchScore: 88,
    investmentScore: 80,
    founded: 2023,
    employees: 31,
    lastRound: "$6M Seed",
    valuation: "$40M",
    revenue: "$1.2M ARR",
    growth: "+290% YoY",
    logo: "⚖️",
    color: "#8B5CF6",
    bulls: [
      "10x faster than human lawyers at 95% accuracy",
      "Top 10 law firms already paying customers",
      "Proprietary legal dataset trained on 50M contracts",
    ],
    risks: ["Incumbent LegalZoom/DocuSign pivoting to AI"],
    founders: [
      { name: "Rachel Torres", role: "CEO", bg: "Ex-BigLaw partner, Harvard Law" },
      { name: "Dev Patel", role: "CTO", bg: "Ex-Anthropic, LLM fine-tuning specialist" },
    ],
    market: { tam: "$18B", sam: "$3B", som: "$150M" },
    aiRec: "Buy — strong founder-market fit, defensible dataset moat",
    tags: ["LegalTech", "AI", "Contracts", "Enterprise"],
  },
  {
    id: "solaris-energy",
    name: "Solaris Energy",
    tagline: "AI-optimized solar grid management for utilities",
    sector: "CleanTech",
    stage: "Series B",
    geography: "Germany",
    matchScore: 82,
    investmentScore: 75,
    founded: 2021,
    employees: 120,
    lastRound: "$35M Series B",
    valuation: "$280M",
    revenue: "$12M ARR",
    growth: "+145% YoY",
    logo: "☀️",
    color: "#F59E0B",
    bulls: [
      "EU energy transition regulation mandating AI grid management by 2027",
      "Contracted with 8 European utilities worth €120M over 5 years",
      "Proven 23% efficiency gains in grid operations",
    ],
    risks: ["High CAPEX requirements, long sales cycles"],
    founders: [
      { name: "Hannah Müller", role: "CEO", bg: "Ex-Siemens Energy VP, 20 yrs utility sector" },
    ],
    market: { tam: "$85B", sam: "$12B", som: "$600M" },
    aiRec: "Hold — great traction but valuation stretched at Series B",
    tags: ["CleanTech", "Energy", "AI", "Infrastructure"],
  },
  {
    id: "edgeml",
    name: "EdgeML",
    tagline: "On-device AI inference — 100x faster, no cloud required",
    sector: "AI/ML",
    stage: "Seed",
    geography: "USA",
    matchScore: 93,
    investmentScore: 85,
    founded: 2024,
    employees: 18,
    lastRound: "$5M Seed",
    valuation: "$35M",
    revenue: "$420K ARR",
    growth: "+380% YoY",
    logo: "🔮",
    color: "#6366F1",
    bulls: [
      "Proprietary compiler achieves 100x inference speedup vs cloud",
      "Samsung + Apple supply chain conversations underway",
      "Patent-protected compression algorithm",
    ],
    risks: ["Big Tech (Apple, Google) building similar in-house"],
    founders: [
      { name: "James Liu", role: "CEO", bg: "Ex-Apple Silicon, M1 chip architect" },
      { name: "Aisha Obi", role: "CTO", bg: "Ex-Qualcomm AI Research" },
    ],
    market: { tam: "$28B", sam: "$4.5B", som: "$220M" },
    aiRec: "Strong Buy — technical depth creates 3-year head start on Big Tech",
    tags: ["AI", "Hardware", "Edge Computing", "B2B"],
  },
  {
    id: "medsync",
    name: "MedSync",
    tagline: "AI care coordination reducing hospital readmissions by 40%",
    sector: "HealthTech",
    stage: "Series A",
    geography: "USA",
    matchScore: 87,
    investmentScore: 78,
    founded: 2022,
    employees: 54,
    lastRound: "$15M Series A",
    valuation: "$95M",
    revenue: "$3.6M ARR",
    growth: "+195% YoY",
    logo: "🏥",
    color: "#10B981",
    bulls: [
      "Proven 40% reduction in 30-day readmissions across 5 hospital networks",
      "Medicare reimbursement code approved — predictable revenue model",
      "Partnerships with 3 of top 10 US health systems",
    ],
    risks: ["Healthcare sales cycles 12–18 months"],
    founders: [
      { name: "Dr. Michael Johnson", role: "CEO", bg: "Ex-Cleveland Clinic CMO" },
    ],
    market: { tam: "$31B", sam: "$5B", som: "$250M" },
    aiRec: "Buy — proven outcomes data is rare and powerful in healthcare",
    tags: ["HealthTech", "AI", "Hospital", "Value-Based Care"],
  },
  {
    id: "voiceflow",
    name: "VoiceFlow AI",
    tagline: "No-code voice AI platform — build Alexa skills in minutes",
    sector: "SaaS",
    stage: "Series B",
    geography: "Canada",
    matchScore: 78,
    investmentScore: 68,
    founded: 2020,
    employees: 180,
    lastRound: "$50M Series B",
    valuation: "$380M",
    revenue: "$22M ARR",
    growth: "+89% YoY",
    logo: "🎙️",
    color: "#EC4899",
    bulls: [
      "Market leader in voice AI dev tools, 200K developers",
      "Strong enterprise tier: Nike, BMW, TD Bank as customers",
    ],
    risks: ["Growth deceleration post-Series A", "OpenAI entering space directly"],
    founders: [
      { name: "Braden Ream", role: "CEO", bg: "Ex-NVIDIA, voice AI research" },
    ],
    market: { tam: "$12B", sam: "$2B", som: "$100M" },
    aiRec: "Watch — strong position but growth slowing, monitor Q3 numbers",
    tags: ["SaaS", "Voice AI", "No-Code", "Developer Tools"],
    portfolio: true,
  },
  {
    id: "carbonzero",
    name: "CarbonZero",
    tagline: "AI-powered carbon credit verification and trading platform",
    sector: "CleanTech",
    stage: "Seed",
    geography: "UK",
    matchScore: 80,
    investmentScore: 72,
    founded: 2023,
    employees: 25,
    lastRound: "$3.5M Seed",
    valuation: "$22M",
    revenue: "$380K ARR",
    growth: "+220% YoY",
    logo: "🌿",
    color: "#059669",
    bulls: [
      "Solving $2B carbon credit fraud problem with satellite + AI verification",
      "EU taxonomy regulation creates forced demand from 2025",
    ],
    risks: ["Regulatory clarity on voluntary carbon markets still uncertain"],
    founders: [
      { name: "Elena Costa", role: "CEO", bg: "Ex-McKinsey Climate Practice, MIT Sloan" },
    ],
    market: { tam: "$50B", sam: "$6B", som: "$300M" },
    aiRec: "Watch — regulatory timing risk, revisit in 6 months",
    tags: ["CleanTech", "Carbon", "ESG", "FinTech"],
  },
  {
    id: "stealth-quantum",
    name: "Quantum Labs",
    tagline: "Post-quantum cryptography as a service for enterprise",
    sector: "Cybersecurity",
    stage: "Pre-seed",
    geography: "Israel",
    matchScore: 86,
    investmentScore: 76,
    founded: 2024,
    employees: 12,
    lastRound: "$2M Pre-seed",
    valuation: "$18M",
    revenue: "$120K ARR",
    growth: "+400% YoY",
    logo: "🔐",
    color: "#DC2626",
    bulls: [
      "NIST post-quantum standards published — enterprise migration mandatory by 2027",
      "Team includes 2 NSA cryptographers",
      "Backed by Israeli intelligence ecosystem",
    ],
    risks: ["Timeline to quantum threat unclear — may be 5–10 years away"],
    founders: [
      { name: "Dr. Yael Cohen", role: "CEO", bg: "Ex-Unit 8200, cryptography PhD" },
    ],
    market: { tam: "$20B", sam: "$3B", som: "$150M" },
    aiRec: "Buy — regulatory tailwind makes this timing-independent",
    tags: ["Cybersecurity", "Quantum", "Cryptography", "Enterprise"],
  },
  {
    id: "supplychain-ai",
    name: "SupplyIQ",
    tagline: "AI supply chain risk detection 90 days before disruption",
    sector: "Enterprise AI",
    stage: "Series A",
    geography: "Germany",
    matchScore: 84,
    investmentScore: 77,
    founded: 2022,
    employees: 72,
    lastRound: "$20M Series A",
    valuation: "$130M",
    revenue: "$6.2M ARR",
    growth: "+175% YoY",
    logo: "🚚",
    color: "#7C3AED",
    bulls: [
      "Post-COVID supply chain paranoia creates permanent demand",
      "Integration with SAP/Oracle creates sticky enterprise contracts",
      "Proven: predicted 3 major supply disruptions 90+ days in advance",
    ],
    risks: ["Enterprise sales cycle 9–12 months slows growth"],
    founders: [
      { name: "Klaus Weber", role: "CEO", bg: "Ex-SAP VP, 18 yrs supply chain" },
    ],
    market: { tam: "$42B", sam: "$7B", som: "$350M" },
    aiRec: "Buy — proven prediction accuracy is strong differentiator",
    tags: ["Enterprise AI", "Supply Chain", "B2B", "Germany"],
  },
  {
    id: "deeplogic",
    name: "DeepLogic AI",
    tagline: "Reasoning engines for enterprise decision automation",
    sector: "AI/ML",
    stage: "Series B",
    geography: "USA",
    matchScore: 90,
    investmentScore: 88,
    founded: 2021,
    employees: 85,
    lastRound: "$45M Series B",
    valuation: "$240M",
    revenue: "$14M ARR",
    growth: "+160% YoY",
    logo: "🧠",
    color: "#8B5CF6",
    bulls: [
      "Portfolio company — invested $2.5M at Series A, now 3.4x",
      "New Series B term sheet at $240M valuation",
      "Reasoning-engine IP licensed by 3 Fortune 100 firms",
    ],
    risks: ["Valuation jump to $240M compresses future return multiple"],
    founders: [
      { name: "Ethan Park", role: "CEO", bg: "Ex-Palantir Forward-Deployed Eng Lead" },
      { name: "Nina Volkov", role: "CTO", bg: "Ex-Google Brain, symbolic reasoning PhD" },
    ],
    market: { tam: "$38B", sam: "$6B", som: "$300M" },
    aiRec: "Follow-on candidate — top-quartile performer, protect ownership",
    tags: ["AI", "Enterprise", "Portfolio", "Reasoning"],
    portfolio: true,
  },
  {
    id: "nexus-health",
    name: "Nexus Health",
    tagline: "Unified patient data layer for hospital networks",
    sector: "HealthTech",
    stage: "Series A",
    geography: "USA",
    matchScore: 83,
    investmentScore: 80,
    founded: 2022,
    employees: 64,
    lastRound: "$16M Series A",
    valuation: "$95M",
    revenue: "$5.2M ARR",
    growth: "+140% YoY",
    logo: "💊",
    color: "#10B981",
    bulls: [
      "Portfolio company — invested $1.8M, now 2.7x",
      "Deployed across 14 hospital networks, 98% retention",
      "HL7 FHIR-native architecture wins IT procurement reviews",
    ],
    risks: ["New competitor raised $30M — monitor closely"],
    founders: [
      { name: "Dr. Amara Osei", role: "CEO", bg: "Ex-Epic Systems product lead, MD" },
    ],
    market: { tam: "$26B", sam: "$4B", som: "$200M" },
    aiRec: "Hold — strong performer, watch competitive entry before follow-on",
    tags: ["HealthTech", "Data", "Portfolio", "B2B"],
    portfolio: true,
  },
  {
    id: "blockvault",
    name: "BlockVault",
    tagline: "Institutional crypto custody with bank-grade compliance",
    sector: "FinTech",
    stage: "Seed",
    geography: "Singapore",
    matchScore: 74,
    investmentScore: 77,
    founded: 2023,
    employees: 31,
    lastRound: "$4M Seed",
    valuation: "$26M",
    revenue: "$1.9M ARR",
    growth: "+240% YoY",
    logo: "🔒",
    color: "#F0C040",
    bulls: [
      "Portfolio company — invested $500K, now 3.6x",
      "MAS-licensed custody, SOC 2 Type II from day one",
      "$2.1B assets under custody from 40 institutional clients",
    ],
    risks: ["Crypto market cyclicality drives AUC volatility"],
    founders: [
      { name: "Daniel Foo", role: "CEO", bg: "Ex-Coinbase Custody, APAC lead" },
      { name: "Marta Kowalski", role: "CTO", bg: "Ex-Standard Chartered digital assets" },
    ],
    market: { tam: "$18B", sam: "$3B", som: "$150M" },
    aiRec: "Hold — let winners run, revisit at Series A for follow-on",
    tags: ["FinTech", "Crypto", "Portfolio", "Custody"],
    portfolio: true,
  },
  {
    id: "terrabyte",
    name: "TerraByte",
    tagline: "Geospatial data platform for climate risk modelling",
    sector: "CleanTech",
    stage: "Series A",
    geography: "UK",
    matchScore: 68,
    investmentScore: 52,
    founded: 2021,
    employees: 48,
    lastRound: "$12M Series A",
    valuation: "$60M",
    revenue: "$2.8M ARR",
    growth: "-22% QoQ",
    logo: "🌍",
    color: "#FB7185",
    bulls: [
      "Portfolio company — invested $3M; current multiple 0.7x",
      "Enterprise contracts remain sticky where deployed",
      "Climate-risk regulation still a long-term tailwind",
    ],
    risks: ["CEO departure — board meeting scheduled", "Revenue declined 22% Q3"],
    founders: [
      { name: "Interim CEO (board search)", role: "CEO", bg: "Founder departed Sep 2026" },
    ],
    market: { tam: "$14B", sam: "$2B", som: "$90M" },
    aiRec: "At risk — AI flagged early-warning signals 6 weeks pre-announcement",
    tags: ["CleanTech", "Geospatial", "Portfolio", "Turnaround"],
    portfolio: true,
  },
  {
    id: "automate-pro",
    name: "AutomatePro",
    tagline: "Workflow automation for mid-market operations teams",
    sector: "SaaS",
    stage: "Series B",
    geography: "USA",
    matchScore: 71,
    investmentScore: 66,
    founded: 2020,
    employees: 110,
    lastRound: "$30M Series B",
    valuation: "$180M",
    revenue: "$9.5M ARR",
    growth: "+89% YoY",
    logo: "⚙️",
    color: "#38BDF8",
    bulls: [
      "Portfolio company — invested $4M, now 1.55x",
      "92% gross retention across 400+ mid-market customers",
      "AI copilot upsell lifting ACV 18% on existing accounts",
    ],
    risks: ["Growth slowing — 89% vs 180% target"],
    founders: [
      { name: "Chris Nguyen", role: "CEO", bg: "Ex-Zapier GM, 2x founder" },
    ],
    market: { tam: "$22B", sam: "$4B", som: "$180M" },
    aiRec: "Hold — yellow flag; growth deceleration needs two clean quarters",
    tags: ["SaaS", "Automation", "Portfolio", "Mid-market"],
    portfolio: true,
  },
  {
    id: "clearsky-data",
    name: "ClearSky Data",
    tagline: "Real-time environmental data infrastructure",
    sector: "Infrastructure",
    stage: "Series A",
    geography: "Europe",
    matchScore: 79,
    investmentScore: 81,
    founded: 2022,
    employees: 42,
    lastRound: "$14M Series A",
    valuation: "$80M",
    revenue: "$4.1M ARR",
    growth: "+170% YoY",
    logo: "☁️",
    color: "#34D399",
    bulls: [
      "Portfolio company — invested $2M, now 2.9x",
      "Sensor network covers 12 EU countries, exclusive data assets",
      "EU open-data directive creates forced institutional demand",
    ],
    risks: ["Hardware supply chain dependency for sensor rollout"],
    founders: [
      { name: "Sofia Lindgren", role: "CEO", bg: "Ex-ESA earth observation programme" },
      { name: "Marc Dubois", role: "CTO", bg: "Ex-Datadog infrastructure team" },
    ],
    market: { tam: "$12B", sam: "$2.5B", som: "$120M" },
    aiRec: "Strong hold — follow-on candidate at Series B",
    tags: ["Infrastructure", "Climate Data", "Portfolio", "EU"],
    portfolio: true,
  },
];

export const portfolio = [
  {
    id: "deeplogic",
    name: "DeepLogic AI",
    sector: "AI/ML",
    stage: "Series B",
    invested: "$2.5M",
    ownership: "4.2%",
    currentValue: "$8.4M",
    multiple: "3.4x",
    irr: "187%",
    investedDate: "2023-03",
    status: "green",
    alerts: [],
    logo: "🧠",
  },
  {
    id: "nexus-health",
    name: "Nexus Health",
    sector: "HealthTech",
    stage: "Series A",
    invested: "$1.8M",
    ownership: "6.1%",
    currentValue: "$4.9M",
    multiple: "2.7x",
    irr: "142%",
    investedDate: "2023-08",
    status: "green",
    alerts: ["New competitor raised $30M — monitor closely"],
    logo: "💊",
  },
  {
    id: "blockvault",
    name: "BlockVault",
    sector: "FinTech",
    stage: "Seed",
    invested: "$500K",
    ownership: "8.5%",
    currentValue: "$1.8M",
    multiple: "3.6x",
    irr: "210%",
    investedDate: "2024-01",
    status: "green",
    alerts: [],
    logo: "🔒",
  },
  {
    id: "terrabyte",
    name: "TerraByte",
    sector: "CleanTech",
    stage: "Series A",
    invested: "$3M",
    ownership: "3.8%",
    currentValue: "$2.1M",
    multiple: "0.7x",
    irr: "-31%",
    investedDate: "2022-11",
    status: "red",
    alerts: ["CEO departure — board meeting scheduled", "Revenue declined 22% Q3"],
    logo: "🌍",
  },
  {
    id: "automate-pro",
    name: "AutomatePro",
    sector: "SaaS",
    stage: "Series B",
    invested: "$4M",
    ownership: "2.9%",
    currentValue: "$6.2M",
    multiple: "1.55x",
    irr: "62%",
    investedDate: "2023-06",
    status: "yellow",
    alerts: ["Growth slowing — 89% vs 180% target"],
    logo: "⚙️",
  },
  {
    id: "clearsky-data",
    name: "ClearSky Data",
    sector: "Infrastructure",
    stage: "Series A",
    invested: "$2M",
    ownership: "5.1%",
    currentValue: "$5.8M",
    multiple: "2.9x",
    irr: "156%",
    investedDate: "2023-04",
    status: "green",
    alerts: [],
    logo: "☁️",
  },
  {
    id: "voiceflow",
    name: "Voiceflow AI",
    sector: "SaaS",
    stage: "Series B",
    invested: "$5M",
    ownership: "3.1%",
    currentValue: "$9.2M",
    multiple: "1.84x",
    irr: "94%",
    investedDate: "2023-11",
    status: "yellow",
    alerts: ["Growth decelerating — 89% vs plan; monitor Q3"],
    logo: "🎙️",
  },
];

export const fundStats = {
  totalAUM: "$48.5M",
  deployedCapital: "$32.1M",
  remainingDryPowder: "$16.4M",
  portfolioValue: "$89.2M",
  unrealisedGain: "+178%",
  tvpi: "2.78x",
  dpi: "0.12x",
  irr: "142%",
  companies: 7,
  followOns: 4,
};

export const agentOutputs: Record<string, {
  market: string;
  technical: string;
  financial: string;
  legal: string;
  founder: string;
  memo: string;
  risks: string[];
  questions: string[];
}> = {
  "nova-ai": {
    market: "TAM of $47B by 2027 in enterprise AI automation. Market growing 68% YoY driven by labor cost pressures. Nova AI targets the middle segment ($10M–$500M revenue companies) — currently underserved by hyperscalers. 3 comparable exits: UiPath ($35B), Automation Anywhere ($6.8B), ServiceNow ($130B). Competitive moat window: 18–24 months before enterprise cloud vendors commoditize.",
    technical: "Proprietary fine-tuning pipeline using RLHF + constitutional AI is genuinely differentiated. Reviewed GitHub (private access via data room) — code quality exceptional, architecture scales horizontally. 14 pending patents covering the core orchestration layer. Technical debt is low. Concerns: single cloud provider dependency (AWS), no on-premise deployment yet — required by 60% of Fortune 500.",
    financial: "$2.4M ARR growing at 340% YoY. Average contract $48K/year. CAC $12K, LTV $240K — LTV:CAC of 20x is exceptional. Rule of 40: 380 + (-40) = 340 — above best-in-class. Burn rate $280K/month, 14 months runway post-raise. Path to profitability at $8M ARR (18 months). Conservative DCF at 25% discount rate: $180M fair value. Current ask at $80M = 2.2x margin of safety.",
    legal: "IP portfolio clean. 3 founder IP assignments signed. No customer data governance issues. GDPR/SOC2 Type II compliant. Two employment agreements need non-compete strengthening — flagged to legal counsel. No outstanding litigation. Previous company (CEO) had clean exit, no IP transfer disputes.",
    founder: "Sarah Chen: DeepMind publication record verified (14 papers, 2,100 citations). MIT PhD confirmed. Previous startup (Cognify) raised $8M, acquired by Salesforce 2021 for $45M. Marcus Webb: OpenAI employment verified via LinkedIn + reference. Built core components of GPT-4 RLHF pipeline per public technical reports. No red flags on background check. Execution speed: 48 hires in 9 months, all senior.",
    memo: "Nova AI represents a compelling Series A opportunity in enterprise AI automation. The company has assembled an exceptional technical team (DeepMind + OpenAI alumni) with proven execution — 48 hires and $2.4M ARR in 9 months. The proprietary fine-tuning pipeline creates a durable 18–24 month technical moat. Market timing is optimal as enterprise AI adoption accelerates. Primary risk is competitive pressure from cloud vendors, mitigated by the head start and patent portfolio. Recommended investment: $3M for 3.75% ownership at $80M pre-money.",
    risks: [
      "Cloud vendor competition risk — AWS/Azure building similar features",
      "Single enterprise customer concentration (top 3 = 48% of ARR)",
      "On-premise deployment gap limits Fortune 500 penetration",
      "Key person dependency on CTO Marcus Webb",
    ],
    questions: [
      "What is the 24-month roadmap for on-premise deployment?",
      "What is the contingency plan if AWS announces a competing feature?",
      "Can you share the churn data — any customers churned in the last 12 months?",
      "How does the proprietary fine-tuning pipeline differ technically from OpenAI fine-tuning API?",
      "What is the vesting cliff for the founding team?",
    ],
  },
};
